{{
    config(
        tags = 'orders'
    )
}}

WITH GROUPED_ORDERS AS (
    SELECT
        USER_ID,
        ORDER_ID,
        COUNT(*) AS ORDERS_ITEMS_COUNT,
        MAX(ORDER_DATE) AS ORDER_DATE
    FROM {{ ref('order_items_fact') }}
    GROUP BY USER_ID, ORDER_ID
),
ORDERS_WITH_LAST_ORDERED_DATE AS (
    SELECT
         *,
         LEAD(ORDER_DATE) OVER(PARTITION BY USER_ID ORDER BY ORDER_DATE) AS NEXT_ORDER_DATE
    FROM
         GROUPED_ORDERS
)
SELECT
    *,
    DATEDIFF(
            days, ORDER_DATE, COALESCE(NEXT_ORDER_DATE, ORDER_DATE)
    ) AS DAYS_BETWEEN_ORDERS
FROM ORDERS_WITH_LAST_ORDERED_DATE
ORDER BY ORDER_ID, ORDER_DATE