-- DB and schema
CREATE OR REPLACE DATABASE ECOM_DB;
USE DATABASE ECOM_DB;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA REPORTING;

-- Storage integration, file format, and stage
CREATE OR REPLACE STORAGE INTEGRATION GCP_INTEGRATION_OBJECT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = GCS
    ENABLED = TRUE
    STORAGE_ALLOWED_LOCATIONS = ('gcs://<< your bucket >>');
DESC STORAGE INTEGRATION GCP_INTEGRATION_OBJECT;

CREATE OR REPLACE FILE FORMAT RAW.CSV_FILE_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1;

CREATE OR REPLACE STAGE RAW.ECOM_STAGE
    STORAGE_INTEGRATION = GCP_INTEGRATION_OBJECT
    URL = 'gcs://<< your bucket >>'
    FILE_FORMAT = RAW.CSV_FILE_FORMAT;
LIST @RAW.ECOM_STAGE;

-- Create transform role and grant all access to it
CREATE OR REPLACE ROLE DBT_TRANSFORM;
GRANT ROLE DBT_TRANSFORM TO ROLE ACCOUNTADMIN;

GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE DBT_TRANSFORM;
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE DBT_TRANSFORM;
GRANT ALL ON DATABASE ECOM_DB to ROLE DBT_TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE ECOM_DB to ROLE DBT_TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ECOM_DB to ROLE DBT_TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA ECOM_DB.RAW to ROLE DBT_TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA ECOM_DB.RAW to ROLE DBT_TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA ECOM_DB.STAGING to ROLE DBT_TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA ECOM_DB.STAGING to ROLE DBT_TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA ECOM_DB.REPORTING to ROLE DBT_TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA ECOM_DB.REPORTING to ROLE DBT_TRANSFORM;

-- Create dbt user and grant transform role
CREATE OR REPLACE NETWORK POLICY DBT_USER_NETWORK_POLICY
  ALLOWED_IP_LIST = ('0.0.0.0/0');
CREATE OR REPLACE USER DBT_USER
  LOGIN_NAME='dbt_user'
  TYPE=SERVICE
  RSA_PUBLIC_KEY="<< your public key>>"
  DEFAULT_ROLE=TRANSFORM
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_NAMESPACE='AIRBNB.RAW'
  COMMENT='DBT user used for data transformation';
GRANT ROLE DBT_TRANSFORM to USER DBT_USER;
