USE DATABASE ECOM_DB;

CREATE OR REPLACE TABLE RAW.PRODUCTS (
    PRODUCT_ID VARCHAR(10),
    PRODUCT_NAME VARCHAR(255),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE DECIMAL(10, 2),
    RATING DECIMAL(3, 2),
    LOADED_AT TIMESTAMPLTZ DEFAULT SYSDATE()
);

CREATE OR REPLACE TABLE RAW.USERS (
    USER_ID VARCHAR(10),
    NAME VARCHAR(255),
    EMAIL VARCHAR(100),
    GENDER VARCHAR(20),
    CITY VARCHAR(50),
    SIGNUP_DATE DATE,
    LOADED_AT TIMESTAMPLTZ DEFAULT SYSDATE()
);

CREATE OR REPLACE TABLE RAW.ORDERS (
    ORDER_ID VARCHAR(10),
    USER_ID VARCHAR(10),
    ORDER_DATE TIMESTAMP,
    ORDER_STATUS VARCHAR(30),
    TOTAL_AMOUNT DECIMAL(10, 2),
    LOADED_AT TIMESTAMPLTZ DEFAULT SYSDATE()
);

CREATE OR REPLACE TABLE RAW.ORDER_ITEMS (
    ORDER_ITEM_ID VARCHAR(10),
    ORDER_ID VARCHAR(10),
    PRODUCT_ID VARCHAR(10),
    USER_ID VARCHAR(10),
    QUANTITY INT,
    ITEM_PRICE DECIMAL(10, 2),
    ITEM_TOTAL DECIMAL(10, 2),
    LOADED_AT TIMESTAMPLTZ DEFAULT SYSDATE()
);