USE DATABASE ECOM_DB;

CREATE OR REPLACE TABLE RAW.PRODUCTS (
    PRODUCT_ID VARCHAR(10),
    PRODUCT_NAME VARCHAR(255),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE DECIMAL(10, 2),
    RATING DECIMAL(3, 2),
    LOADED_AT TIMESTAMPLTZ DEFAULT SYSDATE()
);
